modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "vs_tournament"
version = "${mod_version}"
displayName = "Valkyrien Skies Tournament Reforged"
authors = "alex-s168, Balatan, 411_Cat, blockninja124"
description = '''
A tournament mod for Valkyrien Skies with various mechanical blocks and systems.
'''
logoFile = "icon.png"

[[dependencies.vs_tournament]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId="kotlinforforge"
mandatory=true
versionRange="[4,)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_tournament]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_tournament]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.9,)"
ordering = "AFTER"
side = "BOTH"